version: '3.8'

services:
  web:
    build: .
    container_name: app_ia_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=django-insecure-personal-finance-key-pdv-2026
    restart: always

