# Generated by Django 5.2.17 on 2026-08-20 19:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Conta')),
                ('institution', models.CharField(max_length=100, verbose_name='Instituição')),
                ('account_type', models.CharField(choices=[('CHECKING', 'Conta Corrente'), ('SAVINGS', 'Poupança'), ('INVESTMENT', 'Investimento'), ('CASH', 'Carteira Física'), ('OTHER', 'Outros')], default='CHECKING', max_length=20, verbose_name='Tipo')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Inicial')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Atual')),
                ('color', models.CharField(default='#3b82f6', max_length=20, verbose_name='Cor da UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Cartão')),
                ('total_limit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Limite Total')),
                ('closing_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Fechamento')),
                ('due_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia de Vencimento')),
                ('color', models.CharField(default='#8b5cf6', max_length=20, verbose_name='Cor da UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa')], default='EXPENSE', max_length=20, verbose_name='Tipo')),
                ('icon', models.CharField(default='tag', max_length=50, verbose_name='Ícone')),
                ('color', models.CharField(default='#6b7280', max_length=20, verbose_name='Cor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='finance.category', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data')),
                ('type', models.CharField(choices=[('INCOME', 'Entrada'), ('EXPENSE', 'Saída'), ('TRANSFER', 'Transferência')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Realizada')], default='COMPLETED', max_length=20, verbose_name='Status')),
                ('installment_number', models.IntegerField(default=1, verbose_name='Número da Parcela')),
                ('total_installments', models.IntegerField(default=1, verbose_name='Total de Parcelas')),
                ('invoice_month', models.IntegerField(blank=True, null=True, verbose_name='Mês da Fatura')),
                ('invoice_year', models.IntegerField(blank=True, null=True, verbose_name='Ano da Fatura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.account', verbose_name='Conta Origem/Destino')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.category', verbose_name='Categoria')),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.creditcard', verbose_name='Cartão de Crédito')),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='finance.account', verbose_name='Conta de Destino (Transferências)')),
                ('parent_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('PAID', 'Paga')], default='OPEN', max_length=20, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Pago')),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.creditcard', verbose_name='Cartão')),
                ('paid_from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_invoices', to='finance.account', verbose_name='Pago com a Conta')),
            ],
            options={
                'unique_together': {('credit_card', 'month', 'year')},
            },
        ),
    ]
