# Generated by Django 5.2.17 on 2026-08-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='icon',
            field=models.CharField(default='landmark', max_length=50, verbose_name='Ícone/Logo'),
        ),
    ]
